### ISSUE TITLE
Coordination checklist

### ISSUE THREAD

**Issue by fernandoabolafio** [remixcph/topic-storm#1]
**Foundation**
- [ ] Create prisma schemas and seed file

**Routes**
- [ ] /topic route and base layout (only page title if any - otherwise only route)
- [ ] /topic/:id route and base layout (title, description, votes)

**Topics list**
- [ ] topics search using query params
- [ ] list topic cards (title + number of votes)

**Topic creation**
- [ ] topic creation form & persistence in the database

**Comments**
- [ ] list comments in topic detail view
- [ ] post comment in topic detail view

Jam file: https://jamboard.google.com/d/1I2KtxeSS8NYOqGuYcYp8U2GPhJHl_cgeMlNK5RPjF2Y/edit?usp=sharing

<img width="1517" alt="Screenshot 2022-10-05 at 21 35 15" src="https://user-images.githubusercontent.com/14864439/194147087-f735d682-288d-406f-811b-064962d1e1dd.png">
